import React, { useEffect, useState } from "react";
import { ComponentStory, ComponentMeta } from "@storybook/react";

import BiscuitIndex from "../../pages/index";
// import "../../styles/globals.css";
import "../../styles/globals.css";

// More on default export: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
export default {
  title: "Biscuit-Library/Pages/Biscuit",
  component: BiscuitIndex,

  argTypes: {},
} as ComponentMeta<typeof BiscuitIndex>;

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
export const Template: ComponentStory<typeof BiscuitIndex> = (args) => (
  <Example />
);

export const Example = () => {
  return (
    <BiscuitIndex
      contentObject={{
        eye_0: {
          innerXY: {
            x: 0,
            y: 0,
          },
          innerRotation: 0,
          outerRotation: 0,
          w2h: 1,
          sensitivity: 1,
          movementFactor: 1,
          innerShape: "Circle",
          outerShape: "Circle",
          innerFill: "#000000",
          outerFill: "#ffffff",
          innerStroke: "#000000",
          outerStroke: "#ffffff",
          disableClip: false,
          innerStrokeEnabled: true,
          innerFillEnabled: true,
          outerStrokeEnabled: true,
          outerFillEnabled: true,
          r_outerSize: 0.08,
          r_outer2inner: 0.5,
          r_x: 0.4,
          r_y: 0.3,
          r_innerStrokeWidth: 0.1,
          r_outerStrokeWidth: 0.1,
          active: true,
          contentID: "eye_0",
          r_width: 0.08,
          r_height: 0.08,
          draggable: true,
        },
        rect_0: {
          rotation: 0,
          fill: "#ef5e5d",
          stroke: "#000000",
          draggable: false,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: true,
          fillEnabled: true,
          r_x: 0.5,
          r_y: 0.5,
          r_width: 0.7,
          r_height: 0.95,
          r_strokeWidth: 0.01,
          active: true,
          contentID: "rect_0",
        },
        image_1: {
          name: "Biscuit Image",
          rotation: 0,
          draggable: true,
          cornerRadius: 0,
          keepAspectRatio: true,
          verticalAlign: "middle",
          horizontalAlign: "center",
          fillEnabled: false,
          strokeEnabled: false,
          fill: "#ffffff",
          stroke: "#000000",
          src: "https://res.cloudinary.com/drk1nv578/image/upload/t_optimized/v1612050978/biscuitland/biscuitnoshadow_e49tg3.png",
          r_x: 0.5,
          r_y: 0.5,
          r_width: 0.5,
          r_height: 0.5,
          r_strokeWidth: 0.02,
          active: true,
          contentID: "image_1",
        },
        text_0: {
          rotation: 0,
          fill: "#439ec5",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "center",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: true,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Bebas Neue",
          fontStyle: "normal",
          textContent: "GOODBOY",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.5,
          r_y: 0.16,
          r_width: 0.65,
          r_height: 0.25,
          active: true,
          contentID: "text_0",
        },
        text_1: {
          rotation: 0,
          fill: "#000000",
          stroke: "#ffffff",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "center",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "roboto",
          fontStyle: "normal",
          textContent: "The #1 Dog Magazine for Dogs",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.31,
          r_y: 0.055,
          r_width: 0.3,
          r_height: 0.03,
          active: true,
          contentID: "text_1",
        },
        text_2: {
          rotation: 0,
          fill: "#f6f6af",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: false,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Bebas Neue",
          fontStyle: "normal",
          textContent: "10 FOODS YOUR DOG CRAVES",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.02,
          r_x: 0.275,
          r_y: 0.36,
          r_width: 0.2,
          r_height: 0.2,
          active: true,
          contentID: "text_2",
          outerStrokeEnabled: false,
        },
        text_3: {
          rotation: 0,
          fill: "#ffffff",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Bebas Neue",
          fontStyle: "normal",
          textContent: "Plus...",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.31,
          r_y: 0.49,
          r_width: 0.2,
          r_height: 0.05,
          active: true,
          contentID: "text_3",
          outerStrokeEnabled: false,
        },
        text_4: {
          rotation: 0,
          fill: "#f6f6af",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Roboto Condensed",
          fontStyle: "bold",
          textContent: "Why 80% of Dogs Hate Mustard",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.275,
          r_y: 0.59,
          r_width: 0.2,
          r_height: 0.2,
          active: true,
          contentID: "text_4",
          outerStrokeEnabled: true,
        },
        text_5: {
          rotation: 0,
          fill: "#f6f6af",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Roboto Condensed",
          fontStyle: "bold",
          textContent: "Good Boy of the Week Winner",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.02,
          r_x: 0.7,
          r_y: 0.4,
          r_width: 0.2,
          r_height: 0.15,
          active: true,
          contentID: "text_5",
        },
        text_6: {
          rotation: 0,
          fill: "#000000",
          stroke: "#ffffff",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "right",
          draggable: false,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Bebas Neue",
          fontStyle: "normal",
          textContent: "Revealed...",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.7,
          r_y: 0.3,
          r_width: 0.16,
          r_height: 0.06,
          active: true,
          contentID: "text_6",
        },
        text_7: {
          rotation: 0,
          fill: "#f6f6af",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Roboto Condensed",
          fontStyle: "bold",
          textContent: "Guide to getting rid of the UPS man for good!",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.02,
          r_x: 0.7,
          r_y: 0.54,
          r_width: 0.2,
          r_height: 0.15,
          active: true,
          contentID: "text_7",
        },
        text_8: {
          rotation: 0,
          fill: "#ffffff",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: false,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Bebas Neue",
          fontStyle: "normal",
          textContent: "AND!!",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.02,
          r_x: 0.72,
          r_y: 0.64,
          r_width: 0.25,
          r_height: 0.06,
          active: true,
          contentID: "text_8",
        },
        text_9: {
          rotation: 0,
          fill: "#f6f6af",
          stroke: "#000000",
          textBoxFill: "#0000ff",
          textBoxStroke: "ff0000",
          align: "left",
          draggable: true,
          cornerRadius: 0,
          immediateXY: true,
          strokeEnabled: false,
          fillEnabled: true,
          textBoxStrokeEnabled: false,
          textBoxFillEnabled: false,
          fontFamily: "Roboto Condensed",
          fontStyle: "bold",
          textContent: "Worlds Sexiest Dogs!s",
          minLines: 1,
          maxLines: 10,
          strokeWidthFactor: 0.01,
          r_x: 0.67,
          r_y: 0.72,
          r_width: 0.3,
          r_height: 0.15,
          active: true,
          contentID: "text_9",
        },
      }}
      contentIDs={["rect_0", "eye_0", "image_1", "text_0"]}
    />
  );
};
